name: xmidi_rw
description: Zero dependency midi file reader and writer written on pure dart.
  Part of xmidi project.
  Based on dart_midi package.
version: 0.1.0
homepage: https://github.com/iamguid/xmidi

environment:
  sdk: '>=2.18.0 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
