name: xmidi_utils
description: Some utility methods for MIDI. Part of xmidi project.
version: 0.2.0
homepage: https://github.com/iamguid/xmidi

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
