name: xmidi_player
description: Simple MIDI player written in pure dart.
version: 0.1.0
homepage: https://github.com/iamguid/xmidi

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  xmidi_rw: ^0.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
